-- Generated using https://github.com/codecat/iconfontlua
local utf8 = require('utf8')
return {
	['glass'] = utf8.char(0xf000), -- Glass
	['music'] = utf8.char(0xf001), -- Music
	['search'] = utf8.char(0xf002), -- Search
	['envelope_o'] = utf8.char(0xf003), -- Envelope Outlined
	['heart'] = utf8.char(0xf004), -- Heart
	['star'] = utf8.char(0xf005), -- Star
	['star_o'] = utf8.char(0xf006), -- Star Outlined
	['user'] = utf8.char(0xf007), -- User
	['film'] = utf8.char(0xf008), -- Film
	['th_large'] = utf8.char(0xf009), -- th-large
	['th'] = utf8.char(0xf00a), -- th
	['th_list'] = utf8.char(0xf00b), -- th-list
	['check'] = utf8.char(0xf00c), -- Check
	['times'] = utf8.char(0xf00d), -- Times
	['search_plus'] = utf8.char(0xf00e), -- Search Plus
	['search_minus'] = utf8.char(0xf010), -- Search Minus
	['power_off'] = utf8.char(0xf011), -- Power Off
	['signal'] = utf8.char(0xf012), -- Signal
	['cog'] = utf8.char(0xf013), -- Cog
	['trash_o'] = utf8.char(0xf014), -- Trash Outlined
	['home'] = utf8.char(0xf015), -- home
	['file_o'] = utf8.char(0xf016), -- File Outlined
	['clock_o'] = utf8.char(0xf017), -- Clock Outlined
	['road'] = utf8.char(0xf018), -- road
	['download'] = utf8.char(0xf019), -- Download
	['arrow_circle_o_down'] = utf8.char(0xf01a), -- Arrow Circle Outlined Down
	['arrow_circle_o_up'] = utf8.char(0xf01b), -- Arrow Circle Outlined Up
	['inbox'] = utf8.char(0xf01c), -- inbox
	['play_circle_o'] = utf8.char(0xf01d), -- Play Circle Outlined
	['repeat'] = utf8.char(0xf01e), -- Repeat
	['refresh'] = utf8.char(0xf021), -- refresh
	['list_alt'] = utf8.char(0xf022), -- list-alt
	['lock'] = utf8.char(0xf023), -- lock
	['flag'] = utf8.char(0xf024), -- flag
	['headphones'] = utf8.char(0xf025), -- headphones
	['volume_off'] = utf8.char(0xf026), -- volume-off
	['volume_down'] = utf8.char(0xf027), -- volume-down
	['volume_up'] = utf8.char(0xf028), -- volume-up
	['qrcode'] = utf8.char(0xf029), -- qrcode
	['barcode'] = utf8.char(0xf02a), -- barcode
	['tag'] = utf8.char(0xf02b), -- tag
	['tags'] = utf8.char(0xf02c), -- tags
	['book'] = utf8.char(0xf02d), -- book
	['bookmark'] = utf8.char(0xf02e), -- bookmark
	['print'] = utf8.char(0xf02f), -- print
	['camera'] = utf8.char(0xf030), -- camera
	['font'] = utf8.char(0xf031), -- font
	['bold'] = utf8.char(0xf032), -- bold
	['italic'] = utf8.char(0xf033), -- italic
	['text_height'] = utf8.char(0xf034), -- text-height
	['text_width'] = utf8.char(0xf035), -- text-width
	['align_left'] = utf8.char(0xf036), -- align-left
	['align_center'] = utf8.char(0xf037), -- align-center
	['align_right'] = utf8.char(0xf038), -- align-right
	['align_justify'] = utf8.char(0xf039), -- align-justify
	['list'] = utf8.char(0xf03a), -- list
	['outdent'] = utf8.char(0xf03b), -- Outdent
	['indent'] = utf8.char(0xf03c), -- Indent
	['video_camera'] = utf8.char(0xf03d), -- Video Camera
	['picture_o'] = utf8.char(0xf03e), -- Picture Outlined
	['pencil'] = utf8.char(0xf040), -- pencil
	['map_marker'] = utf8.char(0xf041), -- map-marker
	['adjust'] = utf8.char(0xf042), -- adjust
	['tint'] = utf8.char(0xf043), -- tint
	['pencil_square_o'] = utf8.char(0xf044), -- Pencil Square Outlined
	['share_square_o'] = utf8.char(0xf045), -- Share Square Outlined
	['check_square_o'] = utf8.char(0xf046), -- Check Square Outlined
	['arrows'] = utf8.char(0xf047), -- Arrows
	['step_backward'] = utf8.char(0xf048), -- step-backward
	['fast_backward'] = utf8.char(0xf049), -- fast-backward
	['backward'] = utf8.char(0xf04a), -- backward
	['play'] = utf8.char(0xf04b), -- play
	['pause'] = utf8.char(0xf04c), -- pause
	['stop'] = utf8.char(0xf04d), -- stop
	['forward'] = utf8.char(0xf04e), -- forward
	['fast_forward'] = utf8.char(0xf050), -- fast-forward
	['step_forward'] = utf8.char(0xf051), -- step-forward
	['eject'] = utf8.char(0xf052), -- eject
	['chevron_left'] = utf8.char(0xf053), -- chevron-left
	['chevron_right'] = utf8.char(0xf054), -- chevron-right
	['plus_circle'] = utf8.char(0xf055), -- Plus Circle
	['minus_circle'] = utf8.char(0xf056), -- Minus Circle
	['times_circle'] = utf8.char(0xf057), -- Times Circle
	['check_circle'] = utf8.char(0xf058), -- Check Circle
	['question_circle'] = utf8.char(0xf059), -- Question Circle
	['info_circle'] = utf8.char(0xf05a), -- Info Circle
	['crosshairs'] = utf8.char(0xf05b), -- Crosshairs
	['times_circle_o'] = utf8.char(0xf05c), -- Times Circle Outlined
	['check_circle_o'] = utf8.char(0xf05d), -- Check Circle Outlined
	['ban'] = utf8.char(0xf05e), -- ban
	['arrow_left'] = utf8.char(0xf060), -- arrow-left
	['arrow_right'] = utf8.char(0xf061), -- arrow-right
	['arrow_up'] = utf8.char(0xf062), -- arrow-up
	['arrow_down'] = utf8.char(0xf063), -- arrow-down
	['share'] = utf8.char(0xf064), -- Share
	['expand'] = utf8.char(0xf065), -- Expand
	['compress'] = utf8.char(0xf066), -- Compress
	['plus'] = utf8.char(0xf067), -- plus
	['minus'] = utf8.char(0xf068), -- minus
	['asterisk'] = utf8.char(0xf069), -- asterisk
	['exclamation_circle'] = utf8.char(0xf06a), -- Exclamation Circle
	['gift'] = utf8.char(0xf06b), -- gift
	['leaf'] = utf8.char(0xf06c), -- leaf
	['fire'] = utf8.char(0xf06d), -- fire
	['eye'] = utf8.char(0xf06e), -- Eye
	['eye_slash'] = utf8.char(0xf070), -- Eye Slash
	['exclamation_triangle'] = utf8.char(0xf071), -- Exclamation Triangle
	['plane'] = utf8.char(0xf072), -- plane
	['calendar'] = utf8.char(0xf073), -- calendar
	['random'] = utf8.char(0xf074), -- random
	['comment'] = utf8.char(0xf075), -- comment
	['magnet'] = utf8.char(0xf076), -- magnet
	['chevron_up'] = utf8.char(0xf077), -- chevron-up
	['chevron_down'] = utf8.char(0xf078), -- chevron-down
	['retweet'] = utf8.char(0xf079), -- retweet
	['shopping_cart'] = utf8.char(0xf07a), -- shopping-cart
	['folder'] = utf8.char(0xf07b), -- Folder
	['folder_open'] = utf8.char(0xf07c), -- Folder Open
	['arrows_v'] = utf8.char(0xf07d), -- Arrows Vertical
	['arrows_h'] = utf8.char(0xf07e), -- Arrows Horizontal
	['bar_chart'] = utf8.char(0xf080), -- Bar Chart
	['twitter_square'] = utf8.char(0xf081), -- Twitter Square
	['facebook_square'] = utf8.char(0xf082), -- Facebook Square
	['camera_retro'] = utf8.char(0xf083), -- camera-retro
	['key'] = utf8.char(0xf084), -- key
	['cogs'] = utf8.char(0xf085), -- cogs
	['comments'] = utf8.char(0xf086), -- comments
	['thumbs_o_up'] = utf8.char(0xf087), -- Thumbs Up Outlined
	['thumbs_o_down'] = utf8.char(0xf088), -- Thumbs Down Outlined
	['star_half'] = utf8.char(0xf089), -- star-half
	['heart_o'] = utf8.char(0xf08a), -- Heart Outlined
	['sign_out'] = utf8.char(0xf08b), -- Sign Out
	['linkedin_square'] = utf8.char(0xf08c), -- LinkedIn Square
	['thumb_tack'] = utf8.char(0xf08d), -- Thumb Tack
	['external_link'] = utf8.char(0xf08e), -- External Link
	['sign_in'] = utf8.char(0xf090), -- Sign In
	['trophy'] = utf8.char(0xf091), -- trophy
	['github_square'] = utf8.char(0xf092), -- GitHub Square
	['upload'] = utf8.char(0xf093), -- Upload
	['lemon_o'] = utf8.char(0xf094), -- Lemon Outlined
	['phone'] = utf8.char(0xf095), -- Phone
	['square_o'] = utf8.char(0xf096), -- Square Outlined
	['bookmark_o'] = utf8.char(0xf097), -- Bookmark Outlined
	['phone_square'] = utf8.char(0xf098), -- Phone Square
	['twitter'] = utf8.char(0xf099), -- Twitter
	['facebook'] = utf8.char(0xf09a), -- Facebook
	['github'] = utf8.char(0xf09b), -- GitHub
	['unlock'] = utf8.char(0xf09c), -- unlock
	['credit_card'] = utf8.char(0xf09d), -- credit-card
	['rss'] = utf8.char(0xf09e), -- rss
	['hdd_o'] = utf8.char(0xf0a0), -- HDD
	['bullhorn'] = utf8.char(0xf0a1), -- bullhorn
	['bell_o'] = utf8.char(0xf0f3), -- Bell Outlined
	['certificate'] = utf8.char(0xf0a3), -- certificate
	['hand_o_right'] = utf8.char(0xf0a4), -- Hand Outlined Right
	['hand_o_left'] = utf8.char(0xf0a5), -- Hand Outlined Left
	['hand_o_up'] = utf8.char(0xf0a6), -- Hand Outlined Up
	['hand_o_down'] = utf8.char(0xf0a7), -- Hand Outlined Down
	['arrow_circle_left'] = utf8.char(0xf0a8), -- Arrow Circle Left
	['arrow_circle_right'] = utf8.char(0xf0a9), -- Arrow Circle Right
	['arrow_circle_up'] = utf8.char(0xf0aa), -- Arrow Circle Up
	['arrow_circle_down'] = utf8.char(0xf0ab), -- Arrow Circle Down
	['globe'] = utf8.char(0xf0ac), -- Globe
	['globe_e'] = utf8.char(0xf304), -- Globe
	['globe_w'] = utf8.char(0xf305), -- Globe
	['wrench'] = utf8.char(0xf0ad), -- Wrench
	['tasks'] = utf8.char(0xf0ae), -- Tasks
	['filter'] = utf8.char(0xf0b0), -- Filter
	['briefcase'] = utf8.char(0xf0b1), -- Briefcase
	['arrows_alt'] = utf8.char(0xf0b2), -- Arrows Alt
	['users'] = utf8.char(0xf0c0), -- Users
	['link'] = utf8.char(0xf0c1), -- Link
	['cloud'] = utf8.char(0xf0c2), -- Cloud
	['flask'] = utf8.char(0xf0c3), -- Flask
	['scissors'] = utf8.char(0xf0c4), -- Scissors
	['files_o'] = utf8.char(0xf0c5), -- Files Outlined
	['paperclip'] = utf8.char(0xf0c6), -- Paperclip
	['floppy_o'] = utf8.char(0xf0c7), -- Floppy Outlined
	['square'] = utf8.char(0xf0c8), -- Square
	['bars'] = utf8.char(0xf0c9), -- Bars
	['list_ul'] = utf8.char(0xf0ca), -- list-ul
	['list_ol'] = utf8.char(0xf0cb), -- list-ol
	['strikethrough'] = utf8.char(0xf0cc), -- Strikethrough
	['underline'] = utf8.char(0xf0cd), -- Underline
	['table'] = utf8.char(0xf0ce), -- table
	['magic'] = utf8.char(0xf0d0), -- magic
	['truck'] = utf8.char(0xf0d1), -- truck
	['pinterest'] = utf8.char(0xf0d2), -- Pinterest
	['pinterest_square'] = utf8.char(0xf0d3), -- Pinterest Square
	['google_plus_square'] = utf8.char(0xf0d4), -- Google Plus Square
	['google_plus'] = utf8.char(0xf0d5), -- Google Plus
	['money'] = utf8.char(0xf0d6), -- Money
	['caret_down'] = utf8.char(0xf0d7), -- Caret Down
	['caret_up'] = utf8.char(0xf0d8), -- Caret Up
	['caret_left'] = utf8.char(0xf0d9), -- Caret Left
	['caret_right'] = utf8.char(0xf0da), -- Caret Right
	['columns'] = utf8.char(0xf0db), -- Columns
	['sort'] = utf8.char(0xf0dc), -- Sort
	['sort_desc'] = utf8.char(0xf0dd), -- Sort Descending
	['sort_asc'] = utf8.char(0xf0de), -- Sort Ascending
	['envelope'] = utf8.char(0xf0e0), -- Envelope
	['linkedin'] = utf8.char(0xf0e1), -- LinkedIn
	['undo'] = utf8.char(0xf0e2), -- Undo
	['gavel'] = utf8.char(0xf0e3), -- Gavel
	['tachometer'] = utf8.char(0xf0e4), -- Tachometer
	['comment_o'] = utf8.char(0xf0e5), -- comment-o
	['comments_o'] = utf8.char(0xf0e6), -- comments-o
	['bolt'] = utf8.char(0xf0e7), -- Lightning Bolt
	['sitemap'] = utf8.char(0xf0e8), -- Sitemap
	['umbrella'] = utf8.char(0xf0e9), -- Umbrella
	['clipboard'] = utf8.char(0xf0ea), -- Clipboard
	['lightbulb_o'] = utf8.char(0xf0eb), -- Lightbulb Outlined
	['exchange'] = utf8.char(0xf0ec), -- Exchange
	['cloud_download'] = utf8.char(0xf0ed), -- Cloud Download
	['cloud_upload'] = utf8.char(0xf0ee), -- Cloud Upload
	['user_md'] = utf8.char(0xf0f0), -- user-md
	['stethoscope'] = utf8.char(0xf0f1), -- Stethoscope
	['suitcase'] = utf8.char(0xf0f2), -- Suitcase
	['bell'] = utf8.char(0xf0a2), -- Bell
	['coffee'] = utf8.char(0xf0f4), -- Coffee
	['cutlery'] = utf8.char(0xf0f5), -- Cutlery
	['file_text_o'] = utf8.char(0xf0f6), -- File Text Outlined
	['building_o'] = utf8.char(0xf0f7), -- Building Outlined
	['hospital_o'] = utf8.char(0xf0f8), -- hospital Outlined
	['ambulance'] = utf8.char(0xf0f9), -- ambulance
	['medkit'] = utf8.char(0xf0fa), -- medkit
	['fighter_jet'] = utf8.char(0xf0fb), -- fighter-jet
	['beer'] = utf8.char(0xf0fc), -- beer
	['h_square'] = utf8.char(0xf0fd), -- H Square
	['plus_square'] = utf8.char(0xf0fe), -- Plus Square
	['angle_double_left'] = utf8.char(0xf100), -- Angle Double Left
	['angle_double_right'] = utf8.char(0xf101), -- Angle Double Right
	['angle_double_up'] = utf8.char(0xf102), -- Angle Double Up
	['angle_double_down'] = utf8.char(0xf103), -- Angle Double Down
	['angle_left'] = utf8.char(0xf104), -- angle-left
	['angle_right'] = utf8.char(0xf105), -- angle-right
	['angle_up'] = utf8.char(0xf106), -- angle-up
	['angle_down'] = utf8.char(0xf107), -- angle-down
	['desktop'] = utf8.char(0xf108), -- Desktop
	['laptop'] = utf8.char(0xf109), -- Laptop
	['tablet'] = utf8.char(0xf10a), -- tablet
	['mobile'] = utf8.char(0xf10b), -- Mobile Phone
	['circle_o'] = utf8.char(0xf10c), -- Circle Outlined
	['quote_left'] = utf8.char(0xf10d), -- quote-left
	['quote_right'] = utf8.char(0xf10e), -- quote-right
	['spinner'] = utf8.char(0xf110), -- Spinner
	['circle'] = utf8.char(0xf111), -- Circle
	['reply'] = utf8.char(0xf112), -- Reply
	['github_alt'] = utf8.char(0xf113), -- GitHub Alt
	['folder_o'] = utf8.char(0xf114), -- Folder Outlined
	['folder_open_o'] = utf8.char(0xf115), -- Folder Open Outlined
	['smile_o'] = utf8.char(0xf118), -- Smile Outlined
	['frown_o'] = utf8.char(0xf119), -- Frown Outlined
	['meh_o'] = utf8.char(0xf11a), -- Meh Outlined
	['gamepad'] = utf8.char(0xf11b), -- Gamepad
	['keyboard_o'] = utf8.char(0xf11c), -- Keyboard Outlined
	['flag_o'] = utf8.char(0xf11d), -- Flag Outlined
	['flag_checkered'] = utf8.char(0xf11e), -- flag-checkered
	['terminal'] = utf8.char(0xf120), -- Terminal
	['code'] = utf8.char(0xf121), -- Code
	['reply_all'] = utf8.char(0xf122), -- reply-all
	['star_half_o'] = utf8.char(0xf123), -- Star Half Outlined
	['location_arrow'] = utf8.char(0xf124), -- location-arrow
	['crop'] = utf8.char(0xf125), -- crop
	['code_fork'] = utf8.char(0xf126), -- code-fork
	['chain_broken'] = utf8.char(0xf127), -- Chain Broken
	['question'] = utf8.char(0xf128), -- Question
	['info'] = utf8.char(0xf129), -- Info
	['exclamation'] = utf8.char(0xf12a), -- exclamation
	['superscript'] = utf8.char(0xf12b), -- superscript
	['subscript'] = utf8.char(0xf12c), -- subscript
	['eraser'] = utf8.char(0xf12d), -- eraser
	['puzzle_piece'] = utf8.char(0xf12e), -- Puzzle Piece
	['microphone'] = utf8.char(0xf130), -- microphone
	['microphone_slash'] = utf8.char(0xf131), -- Microphone Slash
	['shield'] = utf8.char(0xf132), -- shield
	['calendar_o'] = utf8.char(0xf133), -- calendar-o
	['fire_extinguisher'] = utf8.char(0xf134), -- fire-extinguisher
	['rocket'] = utf8.char(0xf135), -- rocket
	['maxcdn'] = utf8.char(0xf136), -- MaxCDN
	['chevron_circle_left'] = utf8.char(0xf137), -- Chevron Circle Left
	['chevron_circle_right'] = utf8.char(0xf138), -- Chevron Circle Right
	['chevron_circle_up'] = utf8.char(0xf139), -- Chevron Circle Up
	['chevron_circle_down'] = utf8.char(0xf13a), -- Chevron Circle Down
	['html5'] = utf8.char(0xf13b), -- HTML 5 Logo
	['css3'] = utf8.char(0xf13c), -- CSS 3 Logo
	['anchor'] = utf8.char(0xf13d), -- Anchor
	['unlock_alt'] = utf8.char(0xf13e), -- Unlock Alt
	['bullseye'] = utf8.char(0xf140), -- Bullseye
	['ellipsis_h'] = utf8.char(0xf141), -- Ellipsis Horizontal
	['ellipsis_v'] = utf8.char(0xf142), -- Ellipsis Vertical
	['rss_square'] = utf8.char(0xf143), -- RSS Square
	['play_circle'] = utf8.char(0xf144), -- Play Circle
	['ticket'] = utf8.char(0xf145), -- Ticket
	['minus_square'] = utf8.char(0xf146), -- Minus Square
	['minus_square_o'] = utf8.char(0xf147), -- Minus Square Outlined
	['level_up'] = utf8.char(0xf148), -- Level Up
	['level_down'] = utf8.char(0xf149), -- Level Down
	['check_square'] = utf8.char(0xf14a), -- Check Square
	['pencil_square'] = utf8.char(0xf14b), -- Pencil Square
	['external_link_square'] = utf8.char(0xf14c), -- External Link Square
	['share_square'] = utf8.char(0xf14d), -- Share Square
	['compass'] = utf8.char(0xf14e), -- Compass
	['caret_square_o_down'] = utf8.char(0xf150), -- Caret Square Outlined Down
	['caret_square_o_up'] = utf8.char(0xf151), -- Caret Square Outlined Up
	['caret_square_o_right'] = utf8.char(0xf152), -- Caret Square Outlined Right
	['eur'] = utf8.char(0xf153), -- Euro (EUR)
	['gbp'] = utf8.char(0xf154), -- GBP
	['usd'] = utf8.char(0xf155), -- US Dollar
	['inr'] = utf8.char(0xf156), -- Indian Rupee (INR)
	['jpy'] = utf8.char(0xf157), -- Japanese Yen (JPY)
	['rub'] = utf8.char(0xf158), -- Russian Ruble (RUB)
	['krw'] = utf8.char(0xf159), -- Korean Won (KRW)
	['btc'] = utf8.char(0xf15a), -- Bitcoin (BTC)
	['file'] = utf8.char(0xf15b), -- File
	['file_text'] = utf8.char(0xf15c), -- File Text
	['sort_alpha_asc'] = utf8.char(0xf15d), -- Sort Alpha Ascending
	['sort_alpha_desc'] = utf8.char(0xf15e), -- Sort Alpha Descending
	['sort_amount_asc'] = utf8.char(0xf160), -- Sort Amount Ascending
	['sort_amount_desc'] = utf8.char(0xf161), -- Sort Amount Descending
	['sort_numeric_asc'] = utf8.char(0xf162), -- Sort Numeric Ascending
	['sort_numeric_desc'] = utf8.char(0xf163), -- Sort Numeric Descending
	['thumbs_up'] = utf8.char(0xf164), -- thumbs-up
	['thumbs_down'] = utf8.char(0xf165), -- thumbs-down
	['youtube_square'] = utf8.char(0xf166), -- YouTube Square
	['youtube'] = utf8.char(0xf167), -- YouTube
	['xing'] = utf8.char(0xf168), -- Xing
	['xing_square'] = utf8.char(0xf169), -- Xing Square
	['youtube_play'] = utf8.char(0xf16a), -- YouTube Play
	['dropbox'] = utf8.char(0xf16b), -- Dropbox
	['stack_overflow'] = utf8.char(0xf16c), -- Stack Overflow
	['instagram'] = utf8.char(0xf16d), -- Instagram
	['flickr'] = utf8.char(0xf16e), -- Flickr
	['adn'] = utf8.char(0xf170), -- App.net
	['bitbucket'] = utf8.char(0xf171), -- Bitbucket
	['bitbucket_square'] = utf8.char(0xf172), -- Bitbucket Square
	['tumblr'] = utf8.char(0xf173), -- Tumblr
	['tumblr_square'] = utf8.char(0xf174), -- Tumblr Square
	['long_arrow_down'] = utf8.char(0xf175), -- Long Arrow Down
	['long_arrow_up'] = utf8.char(0xf176), -- Long Arrow Up
	['long_arrow_left'] = utf8.char(0xf177), -- Long Arrow Left
	['long_arrow_right'] = utf8.char(0xf178), -- Long Arrow Right
	['apple'] = utf8.char(0xf179), -- Apple
	['windows'] = utf8.char(0xf17a), -- Windows
	['android'] = utf8.char(0xf17b), -- Android
	['linux'] = utf8.char(0xf17c), -- Linux
	['dribbble'] = utf8.char(0xf17d), -- Dribbble
	['skype'] = utf8.char(0xf17e), -- Skype
	['foursquare'] = utf8.char(0xf180), -- Foursquare
	['trello'] = utf8.char(0xf181), -- Trello
	['female'] = utf8.char(0xf182), -- Female
	['male'] = utf8.char(0xf183), -- Male
	['gratipay'] = utf8.char(0xf184), -- Gratipay (Gittip)
	['sun_o'] = utf8.char(0xf185), -- Sun Outlined
	['moon_o'] = utf8.char(0xf186), -- Moon Outlined
	['archive'] = utf8.char(0xf187), -- Archive
	['bug'] = utf8.char(0xf188), -- Bug
	['vk'] = utf8.char(0xf189), -- VK
	['weibo'] = utf8.char(0xf18a), -- Weibo
	['renren'] = utf8.char(0xf18b), -- Renren
	['pagelines'] = utf8.char(0xf18c), -- Pagelines
	['stack_exchange'] = utf8.char(0xf18d), -- Stack Exchange
	['arrow_circle_o_right'] = utf8.char(0xf18e), -- Arrow Circle Outlined Right
	['arrow_circle_o_left'] = utf8.char(0xf190), -- Arrow Circle Outlined Left
	['caret_square_o_left'] = utf8.char(0xf191), -- Caret Square Outlined Left
	['dot_circle_o'] = utf8.char(0xf192), -- Dot Circle Outlined
	['wheelchair'] = utf8.char(0xf193), -- Wheelchair
	['vimeo_square'] = utf8.char(0xf194), -- Vimeo Square
	['try'] = utf8.char(0xf195), -- Turkish Lira (TRY)
	['plus_square_o'] = utf8.char(0xf196), -- Plus Square Outlined
	['space_shuttle'] = utf8.char(0xf197), -- Space Shuttle
	['slack'] = utf8.char(0xf198), -- Slack Logo
	['envelope_square'] = utf8.char(0xf199), -- Envelope Square
	['wordpress'] = utf8.char(0xf19a), -- WordPress Logo
	['openid'] = utf8.char(0xf19b), -- OpenID
	['university'] = utf8.char(0xf19c), -- University
	['graduation_cap'] = utf8.char(0xf19d), -- Graduation Cap
	['yahoo'] = utf8.char(0xf19e), -- Yahoo Logo
	['google'] = utf8.char(0xf1a0), -- Google Logo
	['reddit'] = utf8.char(0xf1a1), -- reddit Logo
	['reddit_square'] = utf8.char(0xf1a2), -- reddit Square
	['stumbleupon_circle'] = utf8.char(0xf1a3), -- StumbleUpon Circle
	['stumbleupon'] = utf8.char(0xf1a4), -- StumbleUpon Logo
	['delicious'] = utf8.char(0xf1a5), -- Delicious Logo
	['digg'] = utf8.char(0xf1a6), -- Digg Logo
	['drupal'] = utf8.char(0xf1a9), -- Drupal Logo
	['joomla'] = utf8.char(0xf1aa), -- Joomla Logo
	['language'] = utf8.char(0xf1ab), -- Language
	['fax'] = utf8.char(0xf1ac), -- Fax
	['building'] = utf8.char(0xf1ad), -- Building
	['child'] = utf8.char(0xf1ae), -- Child
	['paw'] = utf8.char(0xf1b0), -- Paw
	['spoon'] = utf8.char(0xf1b1), -- spoon
	['cube'] = utf8.char(0xf1b2), -- Cube
	['cubes'] = utf8.char(0xf1b3), -- Cubes
	['behance'] = utf8.char(0xf1b4), -- Behance
	['behance_square'] = utf8.char(0xf1b5), -- Behance Square
	['steam'] = utf8.char(0xf1b6), -- Steam
	['steam_square'] = utf8.char(0xf1b7), -- Steam Square
	['recycle'] = utf8.char(0xf1b8), -- Recycle
	['car'] = utf8.char(0xf1b9), -- Car
	['taxi'] = utf8.char(0xf1ba), -- Taxi
	['tree'] = utf8.char(0xf1bb), -- Tree
	['spotify'] = utf8.char(0xf1bc), -- Spotify
	['deviantart'] = utf8.char(0xf1bd), -- deviantART
	['soundcloud'] = utf8.char(0xf1be), -- SoundCloud
	['database'] = utf8.char(0xf1c0), -- Database
	['file_pdf_o'] = utf8.char(0xf1c1), -- PDF File Outlined
	['file_word_o'] = utf8.char(0xf1c2), -- Word File Outlined
	['file_excel_o'] = utf8.char(0xf1c3), -- Excel File Outlined
	['file_powerpoint_o'] = utf8.char(0xf1c4), -- Powerpoint File Outlined
	['file_image_o'] = utf8.char(0xf1c5), -- Image File Outlined
	['file_archive_o'] = utf8.char(0xf1c6), -- Archive File Outlined
	['file_audio_o'] = utf8.char(0xf1c7), -- Audio File Outlined
	['file_video_o'] = utf8.char(0xf1c8), -- Video File Outlined
	['file_code_o'] = utf8.char(0xf1c9), -- Code File Outlined
	['vine'] = utf8.char(0xf1ca), -- Vine
	['codepen'] = utf8.char(0xf1cb), -- Codepen
	['jsfiddle'] = utf8.char(0xf1cc), -- jsFiddle
	['life_ring'] = utf8.char(0xf1cd), -- Life Ring
	['circle_o_notch'] = utf8.char(0xf1ce), -- Circle Outlined Notched
	['rebel'] = utf8.char(0xf1d0), -- Rebel Alliance
	['empire'] = utf8.char(0xf1d1), -- Galactic Empire
	['git_square'] = utf8.char(0xf1d2), -- Git Square
	['git'] = utf8.char(0xf1d3), -- Git
	['hacker_news'] = utf8.char(0xf1d4), -- Hacker News
	['tencent_weibo'] = utf8.char(0xf1d5), -- Tencent Weibo
	['qq'] = utf8.char(0xf1d6), -- QQ
	['weixin'] = utf8.char(0xf1d7), -- Weixin (WeChat)
	['paper_plane'] = utf8.char(0xf1d8), -- Paper Plane
	['paper_plane_o'] = utf8.char(0xf1d9), -- Paper Plane Outlined
	['history'] = utf8.char(0xf1da), -- History
	['circle_thin'] = utf8.char(0xf1db), -- Circle Outlined Thin
	['header'] = utf8.char(0xf1dc), -- header
	['paragraph'] = utf8.char(0xf1dd), -- paragraph
	['sliders'] = utf8.char(0xf1de), -- Sliders
	['share_alt'] = utf8.char(0xf1e0), -- Share Alt
	['share_alt_square'] = utf8.char(0xf1e1), -- Share Alt Square
	['bomb'] = utf8.char(0xf1e2), -- Bomb
	['futbol_o'] = utf8.char(0xf1e3), -- Futbol Outlined
	['tty'] = utf8.char(0xf1e4), -- TTY
	['binoculars'] = utf8.char(0xf1e5), -- Binoculars
	['plug'] = utf8.char(0xf1e6), -- Plug
	['slideshare'] = utf8.char(0xf1e7), -- Slideshare
	['twitch'] = utf8.char(0xf1e8), -- Twitch
	['yelp'] = utf8.char(0xf1e9), -- Yelp
	['newspaper_o'] = utf8.char(0xf1ea), -- Newspaper Outlined
	['wifi'] = utf8.char(0xf1eb), -- WiFi
	['calculator'] = utf8.char(0xf1ec), -- Calculator
	['paypal'] = utf8.char(0xf1ed), -- Paypal
	['google_wallet'] = utf8.char(0xf1ee), -- Google Wallet
	['cc_visa'] = utf8.char(0xf1f0), -- Visa Credit Card
	['cc_mastercard'] = utf8.char(0xf1f1), -- MasterCard Credit Card
	['cc_discover'] = utf8.char(0xf1f2), -- Discover Credit Card
	['cc_amex'] = utf8.char(0xf1f3), -- American Express Credit Card
	['cc_paypal'] = utf8.char(0xf1f4), -- Paypal Credit Card
	['cc_stripe'] = utf8.char(0xf1f5), -- Stripe Credit Card
	['bell_slash'] = utf8.char(0xf1f6), -- Bell Slash
	['bell_slash_o'] = utf8.char(0xf1f7), -- Bell Slash Outlined
	['trash'] = utf8.char(0xf1f8), -- Trash
	['copyright'] = utf8.char(0xf1f9), -- Copyright
	['at'] = utf8.char(0xf1fa), -- At
	['eyedropper'] = utf8.char(0xf1fb), -- Eyedropper
	['paint_brush'] = utf8.char(0xf1fc), -- Paint Brush
	['birthday_cake'] = utf8.char(0xf1fd), -- Birthday Cake
	['area_chart'] = utf8.char(0xf1fe), -- Area Chart
	['pie_chart'] = utf8.char(0xf200), -- Pie Chart
	['line_chart'] = utf8.char(0xf201), -- Line Chart
	['lastfm'] = utf8.char(0xf202), -- last.fm
	['lastfm_square'] = utf8.char(0xf203), -- last.fm Square
	['toggle_off'] = utf8.char(0xf204), -- Toggle Off
	['toggle_on'] = utf8.char(0xf205), -- Toggle On
	['bicycle'] = utf8.char(0xf206), -- Bicycle
	['bus'] = utf8.char(0xf207), -- Bus
	['ioxhost'] = utf8.char(0xf208), -- ioxhost
	['angellist'] = utf8.char(0xf209), -- AngelList
	['cc'] = utf8.char(0xf20a), -- Closed Captions
	['ils'] = utf8.char(0xf20b), -- Shekel (ILS)
	['meanpath'] = utf8.char(0xf20c), -- meanpath
	['buysellads'] = utf8.char(0xf20d), -- BuySellAds
	['connectdevelop'] = utf8.char(0xf20e), -- Connect Develop
	['dashcube'] = utf8.char(0xf210), -- DashCube
	['forumbee'] = utf8.char(0xf211), -- Forumbee
	['leanpub'] = utf8.char(0xf212), -- Leanpub
	['sellsy'] = utf8.char(0xf213), -- Sellsy
	['shirtsinbulk'] = utf8.char(0xf214), -- Shirts in Bulk
	['simplybuilt'] = utf8.char(0xf215), -- SimplyBuilt
	['skyatlas'] = utf8.char(0xf216), -- skyatlas
	['cart_plus'] = utf8.char(0xf217), -- Add to Shopping Cart
	['cart_arrow_down'] = utf8.char(0xf218), -- Shopping Cart Arrow Down
	['diamond'] = utf8.char(0xf219), -- Diamond
	['ship'] = utf8.char(0xf21a), -- Ship
	['user_secret'] = utf8.char(0xf21b), -- User Secret
	['motorcycle'] = utf8.char(0xf21c), -- Motorcycle
	['street_view'] = utf8.char(0xf21d), -- Street View
	['heartbeat'] = utf8.char(0xf21e), -- Heartbeat
	['venus'] = utf8.char(0xf221), -- Venus
	['mars'] = utf8.char(0xf222), -- Mars
	['mercury'] = utf8.char(0xf223), -- Mercury
	['transgender'] = utf8.char(0xf224), -- Transgender
	['transgender_alt'] = utf8.char(0xf225), -- Transgender Alt
	['venus_double'] = utf8.char(0xf226), -- Venus Double
	['mars_double'] = utf8.char(0xf227), -- Mars Double
	['venus_mars'] = utf8.char(0xf228), -- Venus Mars
	['mars_stroke'] = utf8.char(0xf229), -- Mars Stroke
	['mars_stroke_v'] = utf8.char(0xf22a), -- Mars Stroke Vertical
	['mars_stroke_h'] = utf8.char(0xf22b), -- Mars Stroke Horizontal
	['neuter'] = utf8.char(0xf22c), -- Neuter
	['genderless'] = utf8.char(0xf22d), -- Genderless
	['facebook_official'] = utf8.char(0xf230), -- Facebook Official
	['pinterest_p'] = utf8.char(0xf231), -- Pinterest P
	['whatsapp'] = utf8.char(0xf232), -- What's App
	['server'] = utf8.char(0xf233), -- Server
	['user_plus'] = utf8.char(0xf234), -- Add User
	['user_times'] = utf8.char(0xf235), -- Remove User
	['bed'] = utf8.char(0xf236), -- Bed
	['viacoin'] = utf8.char(0xf237), -- Viacoin (VIA)
	['train'] = utf8.char(0xf238), -- Train
	['subway'] = utf8.char(0xf239), -- Subway
	['medium'] = utf8.char(0xf23a), -- Medium
	['medium_square'] = utf8.char(0xf2f8), -- Medium
	['y_combinator'] = utf8.char(0xf23b), -- Y Combinator
	['optin_monster'] = utf8.char(0xf23c), -- Optin Monster
	['opencart'] = utf8.char(0xf23d), -- OpenCart
	['expeditedssl'] = utf8.char(0xf23e), -- ExpeditedSSL
	['battery_full'] = utf8.char(0xf240), -- Battery Full
	['battery_three_quarters'] = utf8.char(0xf241), -- Battery 3/4 Full
	['battery_half'] = utf8.char(0xf242), -- Battery 1/2 Full
	['battery_quarter'] = utf8.char(0xf243), -- Battery 1/4 Full
	['battery_empty'] = utf8.char(0xf244), -- Battery Empty
	['mouse_pointer'] = utf8.char(0xf245), -- Mouse Pointer
	['i_cursor'] = utf8.char(0xf246), -- I Beam Cursor
	['object_group'] = utf8.char(0xf247), -- Object Group
	['object_ungroup'] = utf8.char(0xf248), -- Object Ungroup
	['sticky_note'] = utf8.char(0xf249), -- Sticky Note
	['sticky_note_o'] = utf8.char(0xf24a), -- Sticky Note Outlined
	['cc_jcb'] = utf8.char(0xf24b), -- JCB Credit Card
	['cc_diners_club'] = utf8.char(0xf24c), -- Diner's Club Credit Card
	['clone'] = utf8.char(0xf24d), -- Clone
	['balance_scale'] = utf8.char(0xf24e), -- Balance Scale
	['hourglass_o'] = utf8.char(0xf250), -- Hourglass Outlined
	['hourglass_start'] = utf8.char(0xf251), -- Hourglass Start
	['hourglass_half'] = utf8.char(0xf252), -- Hourglass Half
	['hourglass_end'] = utf8.char(0xf253), -- Hourglass End
	['hourglass'] = utf8.char(0xf254), -- Hourglass
	['hand_rock_o'] = utf8.char(0xf255), -- Rock (Hand)
	['hand_paper_o'] = utf8.char(0xf256), -- Paper (Hand)
	['hand_scissors_o'] = utf8.char(0xf257), -- Scissors (Hand)
	['hand_lizard_o'] = utf8.char(0xf258), -- Lizard (Hand)
	['hand_spock_o'] = utf8.char(0xf259), -- Spock (Hand)
	['hand_pointer_o'] = utf8.char(0xf25a), -- Hand Pointer
	['hand_peace_o'] = utf8.char(0xf25b), -- Hand Peace
	['trademark'] = utf8.char(0xf25c), -- Trademark
	['registered'] = utf8.char(0xf25d), -- Registered Trademark
	['creative_commons'] = utf8.char(0xf25e), -- Creative Commons
	['gg'] = utf8.char(0xf260), -- GG Currency
	['gg_circle'] = utf8.char(0xf261), -- GG Currency Circle
	['tripadvisor'] = utf8.char(0xf262), -- TripAdvisor
	['odnoklassniki'] = utf8.char(0xf263), -- Odnoklassniki
	['odnoklassniki_square'] = utf8.char(0xf264), -- Odnoklassniki Square
	['get_pocket'] = utf8.char(0xf265), -- Get Pocket
	['wikipedia_w'] = utf8.char(0xf266), -- Wikipedia W
	['safari'] = utf8.char(0xf267), -- Safari
	['chrome'] = utf8.char(0xf268), -- Chrome
	['firefox'] = utf8.char(0xf269), -- Firefox
	['opera'] = utf8.char(0xf26a), -- Opera
	['internet_explorer'] = utf8.char(0xf26b), -- Internet-explorer
	['television'] = utf8.char(0xf26c), -- Television
	['contao'] = utf8.char(0xf26d), -- Contao
	['500px'] = utf8.char(0xf26e), -- 500px
	['amazon'] = utf8.char(0xf270), -- Amazon
	['calendar_plus_o'] = utf8.char(0xf271), -- Calendar Plus Outlined
	['calendar_minus_o'] = utf8.char(0xf272), -- Calendar Minus Outlined
	['calendar_times_o'] = utf8.char(0xf273), -- Calendar Times Outlined
	['calendar_check_o'] = utf8.char(0xf274), -- Calendar Check Outlined
	['industry'] = utf8.char(0xf275), -- Industry
	['map_pin'] = utf8.char(0xf276), -- Map Pin
	['map_signs'] = utf8.char(0xf277), -- Map Signs
	['map_o'] = utf8.char(0xf278), -- Map Outlined
	['map'] = utf8.char(0xf279), -- Map
	['commenting'] = utf8.char(0xf27a), -- Commenting
	['commenting_o'] = utf8.char(0xf27b), -- Commenting Outlined
	['houzz'] = utf8.char(0xf27c), -- Houzz
	['vimeo'] = utf8.char(0xf27d), -- Vimeo
	['black_tie'] = utf8.char(0xf27e), -- Font Awesome Black Tie
	['fonticons'] = utf8.char(0xf280), -- Fonticons
	['reddit_alien'] = utf8.char(0xf281), -- reddit Alien
	['edge'] = utf8.char(0xf282), -- Edge Browser
	['credit_card_alt'] = utf8.char(0xf283), -- Credit Card
	['codiepie'] = utf8.char(0xf284), -- Codie Pie
	['modx'] = utf8.char(0xf285), -- MODX
	['fort_awesome'] = utf8.char(0xf286), -- Fort Awesome
	['usb'] = utf8.char(0xf287), -- USB
	['product_hunt'] = utf8.char(0xf288), -- Product Hunt
	['mixcloud'] = utf8.char(0xf289), -- Mixcloud
	['scribd'] = utf8.char(0xf28a), -- Scribd
	['pause_circle'] = utf8.char(0xf28b), -- Pause Circle
	['pause_circle_o'] = utf8.char(0xf28c), -- Pause Circle Outlined
	['stop_circle'] = utf8.char(0xf28d), -- Stop Circle
	['stop_circle_o'] = utf8.char(0xf28e), -- Stop Circle Outlined
	['shopping_bag'] = utf8.char(0xf290), -- Shopping Bag
	['shopping_basket'] = utf8.char(0xf291), -- Shopping Basket
	['hashtag'] = utf8.char(0xf292), -- Hashtag
	['bluetooth'] = utf8.char(0xf293), -- Bluetooth
	['bluetooth_b'] = utf8.char(0xf294), -- Bluetooth
	['percent'] = utf8.char(0xf295), -- Percent
	['gitlab'] = utf8.char(0xf296), -- GitLab
	['wpbeginner'] = utf8.char(0xf297), -- WPBeginner
	['wpforms'] = utf8.char(0xf298), -- WPForms
	['envira'] = utf8.char(0xf299), -- Envira Gallery
	['universal_access'] = utf8.char(0xf29a), -- Universal Access
	['wheelchair_alt'] = utf8.char(0xf29b), -- Wheelchair Alt
	['question_circle_o'] = utf8.char(0xf29c), -- Question Circle Outlined
	['blind'] = utf8.char(0xf29d), -- Blind
	['audio_description'] = utf8.char(0xf29e), -- Audio Description
	['volume_control_phone'] = utf8.char(0xf2a0), -- Volume Control Phone
	['braille'] = utf8.char(0xf2a1), -- Braille
	['assistive_listening_systems'] = utf8.char(0xf2a2), -- Assistive Listening Systems
	['american_sign_language_interpreting'] = utf8.char(0xf2a3), -- American Sign Language Interpreting
	['deaf'] = utf8.char(0xf2a4), -- Deaf
	['glide'] = utf8.char(0xf2a5), -- Glide
	['glide_g'] = utf8.char(0xf2a6), -- Glide G
	['sign_language'] = utf8.char(0xf2a7), -- Sign Language
	['low_vision'] = utf8.char(0xf2a8), -- Low Vision
	['viadeo'] = utf8.char(0xf2a9), -- Viadeo
	['viadeo_square'] = utf8.char(0xf2aa), -- Viadeo Square
	['snapchat'] = utf8.char(0xf2ab), -- Snapchat
	['snapchat_ghost'] = utf8.char(0xf2ac), -- Snapchat Ghost
	['snapchat_square'] = utf8.char(0xf2ad), -- Snapchat Square
	['first_order'] = utf8.char(0xf2b0), -- First Order
	['yoast'] = utf8.char(0xf2b1), -- Yoast
	['themeisle'] = utf8.char(0xf2b2), -- ThemeIsle
	['google_plus_official'] = utf8.char(0xf2b3), -- Google Plus Official
	['font_awesome'] = utf8.char(0xf2b4), -- Font Awesome
	['handshake_o'] = utf8.char(0xf2b5), -- Handshake Outlined
	['envelope_open'] = utf8.char(0xf2b6), -- Envelope Open
	['envelope_open_o'] = utf8.char(0xf2b7), -- Envelope Open Outlined
	['linode'] = utf8.char(0xf2b8), -- Linode
	['address_book'] = utf8.char(0xf2b9), -- Address Book
	['address_book_o'] = utf8.char(0xf2ba), -- Address Book Outlined
	['address_card'] = utf8.char(0xf2bb), -- Address Card
	['address_card_o'] = utf8.char(0xf2bc), -- Address Card Outlined
	['user_circle'] = utf8.char(0xf2bd), -- User Circle
	['user_circle_o'] = utf8.char(0xf2be), -- User Circle Outlined
	['user_o'] = utf8.char(0xf2c0), -- User Outlined
	['id_badge'] = utf8.char(0xf2c1), -- Identification Badge
	['id_card'] = utf8.char(0xf2c2), -- Identification Card
	['id_card_o'] = utf8.char(0xf2c3), -- Identification Card Outlined
	['quora'] = utf8.char(0xf2c4), -- Quora
	['free_code_camp'] = utf8.char(0xf2c5), -- Free Code Camp
	['telegram'] = utf8.char(0xf2c6), -- Telegram
	['thermometer_full'] = utf8.char(0xf2c7), -- Thermometer Full
	['thermometer_three_quarters'] = utf8.char(0xf2c8), -- Thermometer 3/4 Full
	['thermometer_half'] = utf8.char(0xf2c9), -- Thermometer 1/2 Full
	['thermometer_quarter'] = utf8.char(0xf2ca), -- Thermometer 1/4 Full
	['thermometer_empty'] = utf8.char(0xf2cb), -- Thermometer Empty
	['shower'] = utf8.char(0xf2cc), -- Shower
	['bath'] = utf8.char(0xf2cd), -- Bath
	['podcast'] = utf8.char(0xf2ce), -- Podcast
	['window_maximize'] = utf8.char(0xf2d0), -- Window Maximize
	['window_minimize'] = utf8.char(0xf2d1), -- Window Minimize
	['window_restore'] = utf8.char(0xf2d2), -- Window Restore
	['window_close'] = utf8.char(0xf2d3), -- Window Close
	['window_close_o'] = utf8.char(0xf2d4), -- Window Close Outline
	['bandcamp'] = utf8.char(0xf2d5), -- Bandcamp
	['grav'] = utf8.char(0xf2d6), -- Grav
	['etsy'] = utf8.char(0xf2d7), -- Etsy
	['imdb'] = utf8.char(0xf2d8), -- IMDB
	['ravelry'] = utf8.char(0xf2d9), -- Ravelry
	['eercast'] = utf8.char(0xf2da), -- Eercast
	['microchip'] = utf8.char(0xf2db), -- Microchip
	['snowflake_o'] = utf8.char(0xf2dc), -- Snowflake Outlined
	['superpowers'] = utf8.char(0xf2dd), -- Superpowers
	['wpexplorer'] = utf8.char(0xf2de), -- WPExplorer
	['meetup'] = utf8.char(0xf2e0), -- Meetup
	['mastodon'] = utf8.char(0xf2e1), -- Mastodon
	['mastodon_alt'] = utf8.char(0xf2e2), -- Mastodon Alt
	['fork_awesome'] = utf8.char(0xf2e3), -- Fork Awesome
	['peertube'] = utf8.char(0xf2e4), -- PeerTube
	['diaspora'] = utf8.char(0xf2e5), -- Diaspora*
	['friendica'] = utf8.char(0xf2e6), -- Friendica
	['gnu_social'] = utf8.char(0xf2e7), -- GNU Social
	['liberapay_square'] = utf8.char(0xf2e8), -- Liberapay
	['liberapay'] = utf8.char(0xf2e9), -- Liberapay
	['scuttlebutt'] = utf8.char(0xf2ea), -- Scuttlebutt
	['hubzilla'] = utf8.char(0xf2eb), -- Hubzilla
	['social_home'] = utf8.char(0xf2ec), -- Socialhome
	['artstation'] = utf8.char(0xf2ed), -- ArtStation
	['discord'] = utf8.char(0xf2ee), -- Discord
	['discord_alt'] = utf8.char(0xf2ef), -- Discord
	['patreon'] = utf8.char(0xf2f0), -- Patreon
	['snowdrift'] = utf8.char(0xf2f1), -- Snowdrift
	['activitypub'] = utf8.char(0xf2f2), -- ActivityPub
	['ethereum'] = utf8.char(0xf2f3), -- Ethereum
	['keybase'] = utf8.char(0xf2f4), -- Keybase
	['shaarli'] = utf8.char(0xf2f5), -- Shaarli
	['shaarli_o'] = utf8.char(0xf2f6), -- Shaarli Outlined
	['key_modern'] = utf8.char(0xf2f7), -- Key (Modern)
	['xmpp'] = utf8.char(0xf2f9), -- XMPP
	['archive_org'] = utf8.char(0xf2fc), -- Archive.org
	['freedombox'] = utf8.char(0xf2fd), -- Freedombox
	['facebook_messenger'] = utf8.char(0xf2fe), -- Facebook Messenger
	['debian'] = utf8.char(0xf2ff), -- Debian
	['mastodon_square'] = utf8.char(0xf300), -- Mastodon Square
	['tipeee'] = utf8.char(0xf301), -- Tipeee
	['react'] = utf8.char(0xf302), -- React
	['dogmazic'] = utf8.char(0xf303), -- Dogmazic
	['zotero'] = utf8.char(0xf309), -- Zotero
	['nodejs'] = utf8.char(0xf308), -- Nodejs
	['nextcloud'] = utf8.char(0xf306), -- Nextcloud
	['nextcloud_square'] = utf8.char(0xf307), -- Nextcloud Square
	['hackaday'] = utf8.char(0xf30a), -- Hackaday
	['laravel'] = utf8.char(0xf30b), -- Laravel
	['signalapp'] = utf8.char(0xf30c), -- Signal App
	['gnupg'] = utf8.char(0xf30d), -- GnuPG
	['php'] = utf8.char(0xf30e), -- PHP
	['ffmpeg'] = utf8.char(0xf30f), -- FFmpeg
	['joplin'] = utf8.char(0xf310), -- Joplin
	['syncthing'] = utf8.char(0xf311), -- Syncthing
	['inkscape'] = utf8.char(0xf312), -- Inkscape
	['matrix_org'] = utf8.char(0xf313), -- Matrix.org
	['pixelfed'] = utf8.char(0xf314), -- Pixelfed
	['bootstrap'] = utf8.char(0xf315), -- Bootstrap
	['dev_to'] = utf8.char(0xf316), -- Dev.to
	['hashnode'] = utf8.char(0xf317), -- Hashnode
	['jirafeau'] = utf8.char(0xf318), -- Jirafeau
	['emby'] = utf8.char(0xf319), -- Emby
	['wikidata'] = utf8.char(0xf31a), -- Wikidata
	['gimp'] = utf8.char(0xf31b), -- Gimp
	['c'] = utf8.char(0xf31c), -- C
	['digitalocean'] = utf8.char(0xf31d), -- DigitalOcean
	['att'] = utf8.char(0xf31e), -- AT&T
	['gitea'] = utf8.char(0xf31f), -- Gitea
	['file_epub'] = utf8.char(0xf321), -- EPUB
	['python'] = utf8.char(0xf322), -- Python
	['archlinux'] = utf8.char(0xf323), -- Archlinux
	['pleroma'] = utf8.char(0xf324), -- Pleroma
	['unsplash'] = utf8.char(0xf325), -- Unsplash
	['hackster'] = utf8.char(0xf326), -- Hackster
	['spell_check'] = utf8.char(0xf327), -- Spell check
	['moon'] = utf8.char(0xf328), -- Moon
	['sun'] = utf8.char(0xf329), -- Sun
	['f_droid'] = utf8.char(0xf32a), -- F-droid
	['biometric'] = utf8.char(0xf32b), -- biometric
	['wire'] = utf8.char(0xf32c), -- Wire
	['tor_onion'] = utf8.char(0xf32e), -- Tor Project Onion
	['volume_mute'] = utf8.char(0xf32f), -- volume-mute
	['bell_ringing'] = utf8.char(0xf32d), -- Ringing Bell
	['bell_ringing_o'] = utf8.char(0xf330), -- Ringing Bell Outlined
	['hal'] = utf8.char(0xf333), -- HAL
	['jupyter'] = utf8.char(0xf335), -- Jupyter
	['julia'] = utf8.char(0xf334), -- Julia
	['classicpress'] = utf8.char(0xf331), -- ClassicPress
	['classicpress_circle'] = utf8.char(0xf332), -- ClassicPress Circle
	['open_collective'] = utf8.char(0xf336), -- Open Collective
	['orcid'] = utf8.char(0xf337), -- Orcid Id
	['researchgate'] = utf8.char(0xf338), -- Reasearch Gate
	['funkwhale'] = utf8.char(0xf339), -- Funkwhale
	['askfm'] = utf8.char(0xf33a), -- ASKfm
	['blockstack'] = utf8.char(0xf33b), -- Blockstack
	['boardgamegeek'] = utf8.char(0xf33c), -- Board Game Geek
	['bunny'] = utf8.char(0xf35f), -- Bunny
	['buymeacoffee'] = utf8.char(0xf33d), -- Buy Me A Coffee
	['cc_by'] = utf8.char(0xf33e), -- Creative Commons BY
	['cc_cc'] = utf8.char(0xf33f), -- Creative Commons
	['cc_nc_eu'] = utf8.char(0xf341), -- Creative Commons NC-EU
	['cc_nc_jp'] = utf8.char(0xf342), -- Creative Commons NC-JP
	['cc_nc'] = utf8.char(0xf340), -- Creative Commons NC
	['cc_nd'] = utf8.char(0xf343), -- Creative Commons ND
	['cc_pd'] = utf8.char(0xf344), -- Creative Commons PD
	['cc_remix'] = utf8.char(0xf345), -- Creative Commons Remix
	['cc_sa'] = utf8.char(0xf346), -- Creative Commons SA
	['cc_share'] = utf8.char(0xf347), -- Creative Commons Share
	['cc_zero'] = utf8.char(0xf348), -- Creative Commons Zero
	['conway_glider'] = utf8.char(0xf349), -- Conway Glider
	['csharp'] = utf8.char(0xf34a), -- C#
	['email_bulk'] = utf8.char(0xf34b), -- Email Bulk
	['email_bulk_o'] = utf8.char(0xf34c), -- Email Bulk Outlined
	['gnu'] = utf8.char(0xf34d), -- GNU Operating System
	['google_play'] = utf8.char(0xf34e), -- Google Play
	['heroku'] = utf8.char(0xf34f), -- Heroku
	['home_assistant'] = utf8.char(0xf350), -- Home Assistant
	['java'] = utf8.char(0xf351), -- Java
	['mariadb'] = utf8.char(0xf352), -- MariaDB
	['markdown'] = utf8.char(0xf353), -- Markdown
	['mysql'] = utf8.char(0xf354), -- MySQL
	['nordcast'] = utf8.char(0xf355), -- Nordcast
	['plume'] = utf8.char(0xf356), -- Plume
	['postgresql'] = utf8.char(0xf357), -- PostgreSQL
	['sass_alt'] = utf8.char(0xf359), -- Sass Alternative
	['sass'] = utf8.char(0xf358), -- Sass
	['skate'] = utf8.char(0xf35a), -- Skate
	['sketchfab'] = utf8.char(0xf35b), -- Sketchfab
	['tex'] = utf8.char(0xf35c), -- TeX
	['textpattern'] = utf8.char(0xf35d), -- Textpattern
	['unity'] = utf8.char(0xf35e), -- Unity
}
